import { Permissions } from "detritus-client/lib/constants";

export const DiscordPermissions = {
	[String(Permissions.CREATE_INSTANT_INVITE)]: "Create Instant Invite",
	[String(Permissions.KICK_MEMBERS)]: "Kick Members",
	[String(Permissions.BAN_MEMBERS)]: "Ban Members",
	[String(Permissions.ADMINISTRATOR)]: "Administrator",
	[String(Permissions.MANAGE_CHANNELS)]: "Manage Channels",
	[String(Permissions.MANAGE_GUILD)]: "Manage Guild",
	[String(Permissions.ADD_REACTIONS)]: "Add Reactions",
	[String(Permissions.VIEW_AUDIT_LOG)]: "View Audit Log",
	[String(Permissions.PRIORITY_SPEAKER)]: "Priority Speaker",
	[String(Permissions.STREAM)]: "Stream",
	[String(Permissions.VIEW_CHANNEL)]: "View Channel",
	[String(Permissions.SEND_MESSAGES)]: "Send Messages",
	[String(Permissions.SEND_TTS_MESSAGES)]: "Send TTS Messages",
	[String(Permissions.MANAGE_MESSAGES)]: "Manage Messages",
	[String(Permissions.EMBED_LINKS)]: "Embed Links",
	[String(Permissions.ATTACH_FILES)]: "Attach Files",
	[String(Permissions.READ_MESSAGE_HISTORY)]: "Read Message History",
	[String(Permissions.MENTION_EVERYONE)]: "Mention Everyone",
	[String(Permissions.USE_EXTERNAL_EMOJIS)]: "Use External Emojis",
	[String(Permissions.VIEW_GUILD_ANALYTICS)]: "View Guild Analytics",
	[String(Permissions.CONNECT)]: "Connect",
	[String(Permissions.SPEAK)]: "Speak",
	[String(Permissions.MUTE_MEMBERS)]: "Mute Members",
	[String(Permissions.DEAFEN_MEMBERS)]: "Deafen Members",
	[String(Permissions.MOVE_MEMBERS)]: "Move Members",
	[String(Permissions.USE_VAD)]: "Use VAD",
	[String(Permissions.CHANGE_NICKNAME)]: "Change Nickname",
	[String(Permissions.MANAGE_ROLES)]: "Manage Roles",
	[String(Permissions.MANAGE_WEBHOOKS)]: "Manage Webhooks",
	[String(Permissions.MANAGE_EMOJIS)]: "Manage Emojis",
	[String(Permissions.USE_APPLICATION_COMMANDS)]: "Use Application Commands",
	[String(Permissions.REQUEST_TO_SPEAK)]: "Request To Speak",
	[String(Permissions.MANAGE_EVENTS)]: "Manage Events",
	[String(Permissions.MANAGE_THREADS)]: "Manage Threads",
	[String(Permissions.USE_PUBLIC_THREADS)]: "Use Public Threads",
	[String(Permissions.USE_PRIVATE_THREADS)]: "Use Private Threads",
	[String(Permissions.USE_EXTERNAL_STICKERS)]: "Use External Stickers",
	[String(Permissions.SEND_MESSAGES_IN_THREADS)]: "Send Messages In Threads",
};
